# Generated by Django 2.2.3 on 2021-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodCategory', models.CharField(max_length=50)),
                ('foodItems', models.CharField(max_length=50)),
                ('foodAttribute', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
